version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: air_hq_web
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "${DATABASE_URL:-postgresql://sanjida:KQOB2uRth4gyUVITgxptpQ@adsystem-33547.j77.aws-ap-south-1.cockroachlabs.cloud:26257/adsystem?sslmode=verify-full}"
      NEXTAUTH_URL: "${NEXTAUTH_URL:-http://localhost:3000}"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET:-air-hq-inventory-super-secret-key-2026-baf-secure}"
      NODE_ENV: "production"
